### ISSUE TITLE
آموزش یک مدل زبانی جدید

### ISSUE THREAD

**Issue by Bagherihaali** [Oct4Pie/persian-stt#1]
سلام 
من می خوام یک مدل زبانی جدید برای یک حوزه تخصصی آموزش بدم تا با مدل آکوستیکی که شما منتشر کردی کار کنه، اسکریپت generate_scorer_package یک آرگومان checkpoint داره که چون من چنین پوشه ای ندارم نمی تونم اون رو مقدار بدم، شما از چه alphabet برای آموزش مدل آکوستیک استفاده کردید؟

**Comment by Oct4Pie** [comment]
https://drive.google.com/drive/folders/1NL8YT4JawAoAxbA_baXOA_Id1SaW2Y2d?usp=sharing

سلام، تمام نقاط مقابله و داده های معیاری مدل داخل 
 پوشه checkpoints هست. مدل آخر هم توسط فایل [alphabet.txt](https://github.com/Oct4Pie/persian-stt/files/9610856/alphabet.txt) آموزش داده شده.
امیدوارم به کارتون بیاد.
اگر مشکلی بود به اطلاعم برسونید

**Comment by Bagherihaali** [comment]
ممون 
من موفق شدم با استفاده از پوشه checkpoints مدل زبانی رو آموزش بدم، اما چند نکته برای من سوال بر انگیز بود:
1. چرا الفبایی که استفاده کردید فقط شامل جدا نویسی حروف فارسی نیست و چسبیده نویسی حروف فارسی هم هست، مثلا ما حرف «م» رو جدا می تونیم بنویسیم یا چسبیده به حرف قبلی مثل کلمه «مادر»، فقط الفبای جدا نویسی شده فارسی کافی نیست؟
2. من قصد دارم تا روی یک حوزه تخصصی با گویش محاوره از مدل گفتار به متن coqui استفاده کنم، تست اولیه که با scorer خود شما گرفتم نتیجه wer 45٪ بود و تستی که با scorer خودم گرفتم نتیجه به wer 37% رسید، من سعی کردم بخشی از پیکره متنی که استفاده می کنم از نظرات و پیام های کاربران باشه تا به محاوره نزدیک باشه، به نظرتون اگر داده بیشتری جمع آوری کنم می تونم بهبود بدم مدل رو؟
3. اگر من یک پیکره متنی مناسب با حوزه خودم جمع آوری کنم، چه پردازش های روی متن انجام بدم که با مدل آکوستیک همخوانی داشته باشه؟ همون تابع persianify کافیه؟ این تابع دقیقا چه تغییراتی روی متن میده؟


@Oct4Pie

**Comment by Bagherihaali** [comment]
> ممون من موفق شدم با استفاده از پوشه checkpoints مدل زبانی رو آموزش بدم، اما چند نکته برای من سوال بر انگیز بود:
> 
>     1. چرا الفبایی که استفاده کردید فقط شامل جدا نویسی حروف فارسی نیست و چسبیده نویسی حروف فارسی هم هست، مثلا ما حرف «م» رو جدا می تونیم بنویسیم یا چسبیده به حرف قبلی مثل کلمه «مادر»، فقط الفبای جدا نویسی شده فارسی کافی نیست؟
> 
>     2. من قصد دارم تا روی یک حوزه تخصصی با گویش محاوره از مدل گفتار به متن coqui استفاده کنم، تست اولیه که با scorer خود شما گرفتم نتیجه wer 45٪ بود و تستی که با scorer خودم گرفتم نتیجه به wer 37% رسید، من سعی کردم بخشی از پیکره متنی که استفاده می کنم از نظرات و پیام های کاربران باشه تا به محاوره نزدیک باشه، به نظرتون اگر داده بیشتری جمع آوری کنم می تونم بهبود بدم مدل رو؟
> 
>     3. اگر من یک پیکره متنی مناسب با حوزه خودم جمع آوری کنم، چه پردازش های روی متن انجام بدم که با مدل آکوستیک همخوانی داشته باشه؟ همون تابع persianify کافیه؟ این تابع دقیقا چه تغییراتی روی متن میده؟
> 
> 
> @Oct4Pie

اگر ممکنه من رو راهنمایی کنید

**Comment by tntchack** [comment]
اگر ممکنه من رو راهنمایی کنید

**Comment by Oct4Pie** [comment]
@tntchack 
سلام دوست عزیز، 
بابت این تاخیر عذر میخوام. بنا بر دلایل و شرایطی در دسترس نبودم.
۱. الفبایی که مدل میگیره برای الفابا های لاتین طراحی شده. طوریه که اگر حروف چسبیده تجزیه نشن، فرقی بین «مادر» و «م‌ادر» نیست و مدل توانایی تشخیص کلمات این شکلی رو از دست میده. خود الفبا ساز coqui هم الفبا فارسی رو اینشکلی تجزیه میکنه.
۲. اگر دیتا کافی و با کیفیت در حوزه مورد نظر دارید قطعاً ممکنه. من خودم بعد از بار ها تلاش تونستم به wer زیر ۱۵٪ برسم. کیفیت دیتا خیلی مهمه.
۳. بستگی به حوزه مورد نظر داره. اون تابع برای این طراحی شده که متن های استخراج شده از نت رو تمیز کنه و تنها جملات و کلمات فارسی برگردونه. برای استخراج از سایت، pdf, xml, html, و غیره مناسبه. فرمت دهی هم توسط لایبری فارسی معروف hazm هستش. تنها نکته برای این مرحله اینه که جملات باید مرتب (با فرمت استاندارد) باشن و غلط های دستور زبانی و املایی زیاد نباشن چون مدل از این روش نوشتار الگو بر میداره. بنابراین هر روشی که بتونه این رو حاصل کنه مناسبه.

**Comment by Oct4Pie** [comment]
اگر سوال یا مشکل دیگری هست، لطفاً دوباره موضوع را باز کنید
