### ISSUE TITLE
Compiled windows version?

### ISSUE THREAD

**Issue by rayman3003** [Oct4Pie/persian-stt#2]
Can we have a compiled windows version of the project, in the release section?

**Comment by Oct4Pie** [comment]
Which part are referring to? The release section has the optimized language models that should work with most transcription  tools.

**Comment by rayman3003** [comment]
> Which part are referring to? The release section has the optimized language models that should work with most transcription tools.

Really? So can u tell me how could I use it with **TextAloud**?

**Comment by Oct4Pie** [comment]
Are you trying to do speech-to-text or text-to-speech with that Software?

**Comment by rayman3003** [comment]
> Are you trying to do speech-to-text or text-to-speech with that Software?

Sorry . My bad. I though that TextAloud can do the STT too.

Please tell me the solutions with these two STT apps:

https://www.easyspeech2text.com/

&

VovSoft Speech to Text Converter

**Comment by Oct4Pie** [comment]
I don't use Windows and couldn't use any of the software you mentioned.
Have you tried Coqui's transcription engine (https://stt.readthedocs.io/en/latest/DEPLOYMENT.html#cli-usage)?

**Comment by rayman3003** [comment]
> I don't use Windows and couldn't use any of the software you mentioned.
> Have you tried Coqui's transcription engine (https://stt.readthedocs.io/en/latest/DEPLOYMENT.html#cli-usage)?

I'm not familiar with python; So it is hard for me to use that.

U can install almost all windows apps on linux, by using this app:

https://www.winehq.org/

Just give me an instruction on which file (out of those 4 files in release section of persian-stt) I must download? & where should I put them, to make them work with "easyspeech2text" & "VovSoft Speech to Text Converter"?

**Comment by Oct4Pie** [comment]
[persian_stt.tflite](https://github.com/Oct4Pie/persian-stt/releases/download/v0.1.0/persian_stt.tflite) is the tensor graph that can be used. In fact, all are the model in different formats + one scorer.
'kenlm-persian.scorer' is optional but can be used to increase accuracy.

Also, the cli is not in python. You can easily run it from cmd in Windows.
Use `stt.exe`from [here](https://github.com/coqui-ai/STT/releases/download/v1.4.0/native_client.tflite.Windows.tar.xz) as such:
`./stt.exe --model "persian_stt.tflite" --scorer "kenlm-persian.scorer" --audio input.wav`
